<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Taylor Arnold">

<title>4&nbsp; EDA III: Restructuring Data – Foundations of Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05_collect.html" rel="next">
<link href="./03_graphics.html" rel="prev">
<link href="./img/owl_explore.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-25064e4154141e7ea34817c6f1220590.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_intro.html">Part I: Core</a></li><li class="breadcrumb-item"><a href="./04_combine.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">EDA III: Restructuring Data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Foundations of Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/taylor-arnold/fds-py" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I: Core</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_modify.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">EDA I: Organizing Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_graphics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">EDA II: Visualizing Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_combine.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">EDA III: Restructuring Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_collect.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">EDA IV: Collecting Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Part II: Programming</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_program.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Programming</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_strings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Strings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_dataformats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Data Formats</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_requests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Requests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Part III: Models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_supervised.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Supervised Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_unsupervised.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Unsupervised Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_deeplearning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Deep Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_cnnwordvec.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">CNNs and Word2Vec</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_transferlearn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Transfer Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Part IV: Applications</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16_spatial_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Spatial Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17_temporal_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Temporal Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18_network_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Network Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19_textual_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Textual Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20_image_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Image Data</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Part V: Notes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21_notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Notes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup"><span class="header-section-number">4.1</span> Setup</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">4.2</span> Introduction</a></li>
  <li><a href="#primary-and-foreign-keys" id="toc-primary-and-foreign-keys" class="nav-link" data-scroll-target="#primary-and-foreign-keys"><span class="header-section-number">4.3</span> Primary and Foreign Keys</a></li>
  <li><a href="#joining-by-relation" id="toc-joining-by-relation" class="nav-link" data-scroll-target="#joining-by-relation"><span class="header-section-number">4.4</span> Joining by Relation</a></li>
  <li><a href="#join-examples" id="toc-join-examples" class="nav-link" data-scroll-target="#join-examples"><span class="header-section-number">4.5</span> Join Examples</a></li>
  <li><a href="#conditional-joins" id="toc-conditional-joins" class="nav-link" data-scroll-target="#conditional-joins"><span class="header-section-number">4.6</span> Conditional Joins</a></li>
  <li><a href="#units-of-observation" id="toc-units-of-observation" class="nav-link" data-scroll-target="#units-of-observation"><span class="header-section-number">4.7</span> Units of Observation</a></li>
  <li><a href="#pivot-and-unpivot" id="toc-pivot-and-unpivot" class="nav-link" data-scroll-target="#pivot-and-unpivot"><span class="header-section-number">4.8</span> Pivot and Unpivot</a></li>
  <li><a href="#expand-list-columns" id="toc-expand-list-columns" class="nav-link" data-scroll-target="#expand-list-columns"><span class="header-section-number">4.9</span> Expand List Columns</a></li>
  <li><a href="#coming-from-r-or-pandas" id="toc-coming-from-r-or-pandas" class="nav-link" data-scroll-target="#coming-from-r-or-pandas"><span class="header-section-number">4.10</span> Coming from R or Pandas</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./01_intro.html">Part I: Core</a></li><li class="breadcrumb-item"><a href="./04_combine.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">EDA III: Restructuring Data</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-restructure" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">EDA III: Restructuring Data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Practice Notebooks
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Notebook04a [<a href="https://colab.research.google.com/github/taylor-arnold/fds-py-nb/blob/main/nb/notebook04a.ipynb?hl=en">Colab↗</a>]</li>
<li>Notebook04b [<a href="https://colab.research.google.com/github/taylor-arnold/fds-py-nb/blob/main/nb/notebook04b.ipynb?hl=en">Colab↗</a>]</li>
<li>Notebook04c [<a href="https://colab.research.google.com/github/taylor-arnold/fds-py-nb/blob/main/nb/notebook04c.ipynb?hl=en">Colab↗</a>]</li>
<li>Notebook04d [<a href="https://colab.research.google.com/github/taylor-arnold/fds-py-nb/blob/main/nb/notebook04d.ipynb?hl=en">Colab↗</a>]</li>
</ul>
</div>
</div>
</div>
<section id="setup" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="setup"><span class="header-section-number">4.1</span> Setup</h2>
<p>Load all of the modules and datasets needed for the chapter.</p>
<div id="3fb58ba0" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> polars <span class="im">as</span> pl</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> funs <span class="im">import</span> <span class="op">*</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotnine <span class="im">import</span> <span class="op">*</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> polars <span class="im">import</span> col <span class="im">as</span> c</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>theme_set(theme_minimal())</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>country <span class="op">=</span> pl.read_csv(<span class="st">"data/countries.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="introduction" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="introduction"><span class="header-section-number">4.2</span> Introduction</h2>
<p>In <a href="02_modify.html" class="quarto-xref"><span>Chapter 2</span></a>, we learned to use data operations to modify a dataset in Python. These modifications included taking a subset of a DataFrame, such as filtering rows or selecting a reduced set of columns. We saw how to add new columns and how to rearrange rows by sorting on one or more columns. We also explored grouping and summarizing our data to create a new set of summary statistics that aggregate the original dataset at different levels of granularity. Along the way, we saw how these modifications can help create informative data visualizations, particularly when there is too much data to label every row as a point on a single plot.</p>
<p>In this chapter, we’ll continue exploring how to modify data using increasingly advanced techniques. First, we’ll examine how to combine information from two different data tables. Then we’ll move on to pivots, a relatively complex but powerful method for reshaping data.</p>
</section>
<section id="primary-and-foreign-keys" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="primary-and-foreign-keys"><span class="header-section-number">4.3</span> Primary and Foreign Keys</h2>
<p>Primary keys are a core concept we need to understand to combine two datasets in Python. A <em>primary key</em> consists of one or more columns that can uniquely and minimally identify a row of data. For example, in our <code>country</code> dataset the column <code>iso</code> is a primary key. The column <code>full_name</code> is also a primary key. In database theory a distinction is made between <em>candidate keys</em> (any set of one or more columns that could serve as a primary key) and the specific primary key chosen for a table. This distinction is less applicable to data science work, where we will use the term primary key to refer to any possible way of identifying a row in our dataset.</p>
<p>A <em>foreign key</em> is a primary key from one table that appears in another table. For example, we might have a dataset of customers, with one column indicating the <code>iso</code> of the country in which they live. We join multiple tables by associating the primary key in one table with the matching foreign key in another. Notice that the difference between primary and foreign is the table in which the key appears, not the information itself. The value <code>iso</code> is both a primary key in the countries dataset and a foreign key in the customers dataset. The connection between these two tables is called a <em>relation</em>. This is where the term <em>relational database</em> comes from.</p>
</section>
<section id="joining-by-relation" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="joining-by-relation"><span class="header-section-number">4.4</span> Joining by Relation</h2>
<p>We will start with an abstract example before turning to a specific example using actual DataFrames in Python. Assume we have two tables, <code>table_one</code> and <code>table_two</code>. The column <code>key_col</code> appears in both tables: it is a primary key in <code>table_two</code> and a foreign key in <code>table_one</code>. This means it has a single unique row associated with it in <code>table_two</code> but possibly many instances in <code>table_one</code>.</p>
<p>To join the information in these two tables, we use the <code>.join()</code> method of the table containing the foreign key. The arguments include the second dataset and the name of the key used to combine the tables.</p>
<div id="fa4fc8de" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    table_one</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    .join(table_two, on<span class="op">=</span>c.key_col)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Assuming our data are correctly organized, the output will be a dataset with the same number of rows as <code>table_one</code>, where the first set of columns will also match <code>table_one</code>. After the original columns, there will be a version of all the columns from <code>table_two</code> that correspond to the matching values of our key.</p>
<p>Often some of the values in <code>table_one</code> will not have a matching value in <code>table_two</code>. In that case, the default behavior is to remove rows without matches; this is called an <em>inner join</em>. Alternatively, you can fill missing columns with <code>null</code> values, which results in a <em>left join</em>. We can indicate this to Python as follows:</p>
<div id="d52d7ab1" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    table_one</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    .join(table_two, on<span class="op">=</span>c.key_col, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Left and right tables
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The terminology of “left” and “right” tables comes from thinking about how the join would look when written on a single line. Consider the code <code>table_one.join(table_two)</code>; the first table is to the left of the join function and the second table is to the right of the join function. As a rule of thumb, we try to place the table with the foreign key on the left and the table with the primary key on the right. The reason for this is that the output should match the number of observations in the table with the foreign key, so it typically makes it easier to reason about treating it as a method of the foreign-key table. Note that usually the table with the foreign key will be much larger than the table with the primary key.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Equi-joins: inner, left, right, full, semi, anti, cross
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There are six different options that we can assign to the <code>how</code> parameter in the table join method. The default, <code>inner</code>, returns only rows that match in both tables. <code>Left</code> joins return all rows from the left DataFrame; <code>right</code> joins return all rows from the right DataFrame. <code>Full</code> joins (rarely used) return all rows from both tables. A <code>semi</code> join returns only rows from the left table that have a match in the right table; no additional columns are added. An <code>anti</code> join returns only rows in the left table that do not match any rows in the right table. These six options are called equi-joins because they work by finding where the key(s) in one table are equal to the key(s) in another table.</p>
<p>A cross join returns all combinations of rows from the two tables, with no key required. It has several interesting applications, which we will see in later chapters.</p>
</div>
</div>
</div>
<p>There are several other modifications that we can apply to the basic syntax. For example, if our key has multiple columns, we can pass a list to <code>on</code> instead of a single value. Here is the code to join on two matching columns from the two DataFrames.</p>
<div id="3f87bf55" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    table_one</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    .join(table_two, on<span class="op">=</span>[c.key_col1, c.key_col2])</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Or, if the key has different names in the two tables, we can describe them with <code>on_left</code> (the first table) and <code>on_right</code> (the second table). These can be individual values or lists, where each element in one list corresponds to the element in the other.</p>
<div id="8d039838" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    table_one</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    .join(table_two, on_left<span class="op">=</span>c.key_col1, on_left<span class="op">=</span>c.key_col1)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that Python will let you join on any set of columns that match between the two tables. The results can be surprising, and possibly very large, if we are not sure that the join column(s) are a primary key in one of the tables. Avoid joins that do not follow the pattern here (foreign key in the left table and a primary key in the right table).</p>
</section>
<section id="join-examples" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="join-examples"><span class="header-section-number">4.5</span> Join Examples</h2>
<p>The code outline in the previous section should make more sense once we see examples using actual datasets. To do this, we need multiple datasets that we can join together. We will create a smaller version of the <code>country</code> dataset that contains only two columns, which makes it easier to view the results without scrolling. We also load a dataset of country borders, where each row shows the relationship between a country and one of its neighbors.</p>
<div id="284b9809" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>c_sml <span class="op">=</span> country.select(c.iso, c.gini)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>border <span class="op">=</span> pl.read_csv(<span class="st">"data/countries_borders.csv"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>border</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (829, 2)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
</tr>
<tr class="even">
<th>str</th>
<th>str</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"TJK"</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"TKM"</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We can use a relational join to add the Gini coefficient for the country referenced in the border data. Note that <code>iso</code> is present in both tables; it’s a primary key in <code>c_sml</code> and a foreign key in <code>border</code>. We can join them using the code below.</p>
<div id="95085055" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    border</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    .join(c_sml, on<span class="op">=</span>c.iso)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (641, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
<th data-quarto-table-cell-role="th">gini</th>
</tr>
<tr class="even">
<th>str</th>
<th>str</th>
<th>f64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"TJK"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"TKM"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
<td>57.1</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
<td>50.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
<td>50.3</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
<td>50.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
<td>50.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Notice that the Gini coefficient of the base country has been added to the data. The first five rows all correspond to borders with Afghanistan and therefore the same value of the Gini coefficient (27.8) is duplicated for each of the rows. Similarly, the last four rows correspond to Zimbabwe and repeat the Gini coefficient value of 50.3 in each. As with other data methods we use, the <code>.join()</code> method returns a new dataset without modifying the original data. We would need to save the output if we wanted to work further with the results.</p>
<p>The DataFrame after the join has only 641 observations compared to the 829 observations in the original. The reason is that our <code>country</code> data only contains those countries for which we have full economic data. This means that some of the countries in <code>border</code> do not have an entry in <code>c_sml</code>. The default relational join is an inner join, so these missing corresponding rows are removed from the result. Changing to a left join restores the DataFrame to the same number of observations as the original <code>border</code> data.</p>
<div id="af10ce74" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    border</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    .join(c_sml, on<span class="op">=</span>c.iso, how<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (829, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
<th data-quarto-table-cell-role="th">gini</th>
</tr>
<tr class="even">
<th>str</th>
<th>str</th>
<th>f64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"TJK"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"TKM"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
<td>57.1</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
<td>50.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
<td>50.3</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
<td>50.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
<td>50.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>So far, we have added the Gini coefficient of the base country. We could also add the coefficient of the bordering country by associating the column <code>iso_neighbor</code> with the column <code>iso</code> in our countries DataFrame. Here is the code to add the neighboring Gini coefficient.</p>
<div id="4d8472f0" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    border</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    .join(c_sml, left_on<span class="op">=</span>c.iso_neighbor, right_on<span class="op">=</span>c.iso)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (667, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
<th data-quarto-table-cell-role="th">gini</th>
</tr>
<tr class="even">
<th>str</th>
<th>str</th>
<th>f64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
<td>40.9</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
<td>29.6</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
<td>38.2</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"TJK"</td>
<td>34.0</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"UZB"</td>
<td>35.3</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
<td>50.3</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
<td>53.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
<td>54.0</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
<td>63.1</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
<td>57.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>What if we wanted to add the Gini coefficient to both countries in each row? This requires doing two separate joins, one after the other. In the second join, we add the suffix <code>_neighbor</code> to the Gini coefficient to distinguish the two scores in the output.</p>
<div id="612d52cc" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    border</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    .join(c_sml, on<span class="op">=</span>c.iso)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    .join(c_sml, left_on<span class="op">=</span>c.iso_neighbor, right_on<span class="op">=</span>c.iso, suffix<span class="op">=</span><span class="st">"_neighbor"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (523, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">iso_neighbor</th>
<th data-quarto-table-cell-role="th">gini</th>
<th data-quarto-table-cell-role="th">gini_neighbor</th>
</tr>
<tr class="even">
<th>str</th>
<th>str</th>
<th>f64</th>
<th>f64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>"IRN"</td>
<td>27.8</td>
<td>40.9</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"PAK"</td>
<td>27.8</td>
<td>29.6</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"CHN"</td>
<td>27.8</td>
<td>38.2</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>"TJK"</td>
<td>27.8</td>
<td>34.0</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>"UZB"</td>
<td>27.8</td>
<td>35.3</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZMB"</td>
<td>"ZWE"</td>
<td>57.1</td>
<td>50.3</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"BWA"</td>
<td>50.3</td>
<td>53.3</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"MOZ"</td>
<td>50.3</td>
<td>54.0</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>"ZAF"</td>
<td>50.3</td>
<td>63.1</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>"ZMB"</td>
<td>50.3</td>
<td>57.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>As noted above, we can add the option <code>how=</code> with the values <code>inner</code> (default), <code>left</code>, <code>right</code>, or <code>outer</code> to indicate what should happen when keys appear only in one table. Left joins retain all keys from the first (left) table, right joins retain all keys from the second (right) table, and outer joins retain all keys. When there is no matching value in the other table, <code>null</code> values are filled in. The default, <code>inner</code>, is often a good choice to avoid missing values.</p>
<p>Another use of a key-based join is to determine which elements match between one table and another without adding any extra columns. These are called filtering joins because they act like the <code>.filter</code> method in that they select a subset of rows. There are two variants: a semi-join retains only those rows that have a match in the second table, and an anti-join retains only those rows that do not. When there is only a single key, semi- and anti-joins can be replaced by a call to <code>isin</code>. The real power comes when there are multiple keys and we want to know whether a specific combination of keys matches (or does not match) those found in another table.</p>
</section>
<section id="conditional-joins" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="conditional-joins"><span class="header-section-number">4.6</span> Conditional Joins</h2>
<p>In this section, we introduce two additional kinds of joins that are helpful when working with certain types of complex data. Both of these allow us to join by relationships between keys that do not require values to be exactly equal. To start, let’s create two subsets of our <code>countries</code> data, separating out countries in Africa and in Asia, and sorting by the Gini coefficient. We remove any missing values from the output.</p>
<div id="18bd5d6f" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>africa <span class="op">=</span> (</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    country</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.region <span class="op">==</span> <span class="st">"Africa"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    .select(c.full_name, c.gini)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    .sort(c.gini)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    .drop_nulls()</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>asia <span class="op">=</span> (</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    country</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(c.region <span class="op">==</span> <span class="st">"Asia"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    .select(c.full_name, c.gini)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    .sort(c.gini)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    .drop_nulls()</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The function <code>.join_asof</code> combines two datasets by matching each row in the first (left) dataset to the nearest value in the second (right) dataset based on numeric values in a specified pair of columns. It always returns a dataset with the same number of rows as the first (left) dataset. The function is optimized to do this quickly even for large datasets; to achieve this, it requires that both datasets be sorted by the join key before being called. Below is an example where we associate each African country with the nearest Asian country in terms of their Gini coefficient. We set <code>coalesce=False</code> to ensure the matching country’s Gini coefficient is retained in the output.</p>
<div id="29d01dab" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    africa</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    .join_asof(asia, on<span class="op">=</span>c.gini, strategy<span class="op">=</span><span class="st">"nearest"</span>, coalesce<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (35, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">full_name</th>
<th data-quarto-table-cell-role="th">gini</th>
<th data-quarto-table-cell-role="th">full_name_right</th>
<th data-quarto-table-cell-role="th">gini_right</th>
</tr>
<tr class="even">
<th>str</th>
<th>f64</th>
<th>str</th>
<th>f64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Guinea"</td>
<td>29.6</td>
<td>"Pakistan"</td>
<td>29.6</td>
</tr>
<tr class="even">
<td>"Egypt"</td>
<td>31.5</td>
<td>"Korea, Republic of"</td>
<td>31.4</td>
</tr>
<tr class="odd">
<td>"Mauritania"</td>
<td>32.6</td>
<td>"Mongolia"</td>
<td>32.7</td>
</tr>
<tr class="even">
<td>"Ethiopia"</td>
<td>35.0</td>
<td>"Thailand"</td>
<td>35.0</td>
</tr>
<tr class="odd">
<td>"Nigeria"</td>
<td>35.1</td>
<td>"Thailand"</td>
<td>35.0</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"Botswana"</td>
<td>53.3</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="even">
<td>"Mozambique"</td>
<td>54.0</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="odd">
<td>"Zambia"</td>
<td>57.1</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="even">
<td>"Namibia"</td>
<td>59.1</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="odd">
<td>"South Africa"</td>
<td>63.1</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The original motivation for the <code>.join_asof</code> method was to join two time-series datasets. The idea is that we might want the current (most recent) value from one table relative to another. Hence the function’s name and the fact that it uses the <code>backward</code> strategy by default to find the nearest value in the second dataset that is less than (i.e., earlier than) the value in the first. You can set the strategy to <code>forward</code> to look in the other direction, or to <code>nearest</code> to find the closest value. You can also add additional keys with the <code>by</code>, <code>by_left</code>, or <code>by_right</code> options; these keys must match exactly before performing the nearest search. The tables must be pre-sorted by the join key(s) for the function to work.</p>
<p>If we need to do more exotic joins between two tables, we can use the <code>.join_where</code> method. It takes one or more expressions in the same format used by the <code>.filter</code> method to specify exactly which pairs of rows to keep in the joined dataset. To refer to columns that share the same name in both datasets, use the <code>_right</code> suffix to indicate the second dataset. Below is an example that finds all pairs of countries in Africa and Asia where the difference in the Gini coefficient is less than 5.</p>
<div id="c0465585" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    africa</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    .join_where(</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>        asia,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>        (c.gini <span class="op">-</span> c.gini_right).<span class="bu">abs</span>() <span class="op">&lt;</span> <span class="dv">5</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (414, 4)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">full_name</th>
<th data-quarto-table-cell-role="th">gini</th>
<th data-quarto-table-cell-role="th">full_name_right</th>
<th data-quarto-table-cell-role="th">gini_right</th>
</tr>
<tr class="even">
<th>str</th>
<th>f64</th>
<th>str</th>
<th>f64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Guinea"</td>
<td>29.6</td>
<td>"Armenia"</td>
<td>25.2</td>
</tr>
<tr class="even">
<td>"Guinea"</td>
<td>29.6</td>
<td>"United Arab Emirates"</td>
<td>26.0</td>
</tr>
<tr class="odd">
<td>"Guinea"</td>
<td>29.6</td>
<td>"Azerbaijan"</td>
<td>26.6</td>
</tr>
<tr class="even">
<td>"Guinea"</td>
<td>29.6</td>
<td>"Afghanistan"</td>
<td>27.8</td>
</tr>
<tr class="odd">
<td>"Guinea"</td>
<td>29.6</td>
<td>"Kazakhstan"</td>
<td>27.8</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"Cameroon"</td>
<td>46.6</td>
<td>"Philippines"</td>
<td>42.3</td>
</tr>
<tr class="even">
<td>"Cameroon"</td>
<td>46.6</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="odd">
<td>"Burkina Faso"</td>
<td>47.3</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="even">
<td>"Congo"</td>
<td>48.9</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
<tr class="odd">
<td>"Zimbabwe"</td>
<td>50.3</td>
<td>"Malaysia"</td>
<td>46.2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>This method can be slow because it needs to manually check every combination of rows in the two datasets. However, it is very powerful and useful when combining two reasonably sized datasets in a complex way. Notice that we could obtain the same result by starting with a cross join (which returns every combination of rows) and then applying a filter. The benefit of the <code>.join_where</code> is that it avoids having to store in memory all combinations of non-matching rows by effectively combining the cross join and filtering into a single step.</p>
</section>
<section id="units-of-observation" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="units-of-observation"><span class="header-section-number">4.7</span> Units of Observation</h2>
<p>When designing a way to store tabular data, we often must decide whether to favor many rows and few columns or many columns and few rows. A related decision, particularly when choosing a format with more columns, is what information to store in columns versus rows. In some cases the answers are clear and obvious. In others, there are trade-offs about which types of analyses will be easiest or hardest to perform with the data. Let’s work through an example.</p>
<p>Assume that you are a biologist tracking the heights of 100 plants over the next 14 days. There are several different ways that this data could be collected. We could have each day’s measurements in a column and each plant as a row. We could have each plant as a column and each day as a row. Or we could have a row for each combination of plant and day, with <code>100*14 = 1,400</code> rows and three columns (plant ID, day ID, and height).</p>
<p>A core data-science concept will help us distinguish the three cases above. A <em>unit of observation</em> is the entity about which data are collected and recorded in a dataset. In other words, it is the “who” or “what” that each row of the table represents. In the example with one row for each plant and one column for each day, the unit of observation is a <em>plant</em>. In the example with one row for each day and one column for each plant, the unit of observation is a <em>day</em>. In the final example, the one with 1,400 rows, we call the unit of observation <em>plant × day</em> (read “plant crossed with day”), which means each row corresponds to a unique combination of one plant and one day. The key takeaway is that once we have picked the unit of observation, there is only a single way to construct our data table. Choosing the right unit of observation for our data will be a central concern in the next chapter.</p>
<p>Note that the concept of a unit of observation is closely linked to that of a primary key. By definition, a primary key must uniquely identify the “what” of the unit of observation. For example, a primary key for a table whose unit of observation is a plant must uniquely identify each plant. Likewise, a table with a <em>plant × day</em> unit of observation needs a key that uniquely identifies both the plant and the day.</p>
</section>
<section id="pivot-and-unpivot" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="pivot-and-unpivot"><span class="header-section-number">4.8</span> Pivot and Unpivot</h2>
<p>Sometimes the unit of observation in which a data table is stored does not match the unit needed for our analysis. If the stored format uses a compound unit of observation, we can simplify it by using an aggregation to remove one or more components. For example, we could group a <em>plant × day</em> table by plant ID and calculate summary statistics (such as the maximum height over all days) to generate a dataset with <em>plant</em> as the unit of observation. While aggregations are useful, by design they remove information present in the original dataset. Other times, we want to restructure the unit of observation without losing or adding any information—we simply need the data in a different shape for a particular analysis or visualization. To do this, we can use one of two additional data manipulation functions.</p>
<p>Consider the <code>cellphone</code> dataset; we show its first few rows below. The unit of observation is <em>year × country</em>: each row gives the number of cellphones per 100 people for that year and country.</p>
<div id="8f9456a1" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>cellphone <span class="op">=</span> pl.read_csv(<span class="st">"data/countries_cellphone.csv"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>cellphone</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3_480, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iso</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">cell</th>
</tr>
<tr class="even">
<th>str</th>
<th>i64</th>
<th>f64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"AFG"</td>
<td>2003</td>
<td>0.87978</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>2004</td>
<td>2.54662</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>2005</td>
<td>4.91711</td>
</tr>
<tr class="even">
<td>"AFG"</td>
<td>2006</td>
<td>9.9133</td>
</tr>
<tr class="odd">
<td>"AFG"</td>
<td>2007</td>
<td>18.0167</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>2018</td>
<td>85.8627</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>2019</td>
<td>86.4094</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>2020</td>
<td>84.9604</td>
</tr>
<tr class="even">
<td>"ZWE"</td>
<td>2021</td>
<td>90.2538</td>
</tr>
<tr class="odd">
<td>"ZWE"</td>
<td>2022</td>
<td>88.9958</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>We could have stored this dataset in a format where the unit of observation was <em>year</em> and each country had its own column. What if we want to work with the data in that format? For example, if we wanted to compute the difference in cellphone ownership between the United States and Canada, we would need the data in this format. We can convert our dataset using the <code>.pivot()</code> method, which requires indicating which column will be used to index the output (this becomes the unit of observation), which column will be used to create the new columns, and which column contains the values that will fill the table.</p>
<div id="c23d5967" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>cell_wide <span class="op">=</span> (</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    cellphone</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    .pivot(index<span class="op">=</span><span class="st">"year"</span>, on<span class="op">=</span><span class="st">"iso"</span>, values<span class="op">=</span><span class="st">"cell"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>cell_wide</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (20, 175)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">AFG</th>
<th data-quarto-table-cell-role="th">AGO</th>
<th data-quarto-table-cell-role="th">ALB</th>
<th data-quarto-table-cell-role="th">AND</th>
<th data-quarto-table-cell-role="th">ARE</th>
<th data-quarto-table-cell-role="th">ARG</th>
<th data-quarto-table-cell-role="th">ARM</th>
<th data-quarto-table-cell-role="th">AUS</th>
<th data-quarto-table-cell-role="th">AUT</th>
<th data-quarto-table-cell-role="th">AZE</th>
<th data-quarto-table-cell-role="th">BDI</th>
<th data-quarto-table-cell-role="th">BEL</th>
<th data-quarto-table-cell-role="th">BEN</th>
<th data-quarto-table-cell-role="th">BFA</th>
<th data-quarto-table-cell-role="th">BGD</th>
<th data-quarto-table-cell-role="th">BGR</th>
<th data-quarto-table-cell-role="th">BHR</th>
<th data-quarto-table-cell-role="th">BHS</th>
<th data-quarto-table-cell-role="th">BIH</th>
<th data-quarto-table-cell-role="th">BLR</th>
<th data-quarto-table-cell-role="th">BLZ</th>
<th data-quarto-table-cell-role="th">BOL</th>
<th data-quarto-table-cell-role="th">BRA</th>
<th data-quarto-table-cell-role="th">BRB</th>
<th data-quarto-table-cell-role="th">BRN</th>
<th data-quarto-table-cell-role="th">BTN</th>
<th data-quarto-table-cell-role="th">BWA</th>
<th data-quarto-table-cell-role="th">CAF</th>
<th data-quarto-table-cell-role="th">CAN</th>
<th data-quarto-table-cell-role="th">CHE</th>
<th data-quarto-table-cell-role="th">CHL</th>
<th data-quarto-table-cell-role="th">CHN</th>
<th data-quarto-table-cell-role="th">CIV</th>
<th data-quarto-table-cell-role="th">CMR</th>
<th data-quarto-table-cell-role="th">COD</th>
<th data-quarto-table-cell-role="th">COG</th>
<th data-quarto-table-cell-role="th">…</th>
<th data-quarto-table-cell-role="th">SEN</th>
<th data-quarto-table-cell-role="th">SGP</th>
<th data-quarto-table-cell-role="th">SLB</th>
<th data-quarto-table-cell-role="th">SLV</th>
<th data-quarto-table-cell-role="th">SMR</th>
<th data-quarto-table-cell-role="th">SOM</th>
<th data-quarto-table-cell-role="th">STP</th>
<th data-quarto-table-cell-role="th">SUR</th>
<th data-quarto-table-cell-role="th">SVK</th>
<th data-quarto-table-cell-role="th">SVN</th>
<th data-quarto-table-cell-role="th">SWE</th>
<th data-quarto-table-cell-role="th">SWZ</th>
<th data-quarto-table-cell-role="th">SYC</th>
<th data-quarto-table-cell-role="th">SYR</th>
<th data-quarto-table-cell-role="th">TCD</th>
<th data-quarto-table-cell-role="th">TGO</th>
<th data-quarto-table-cell-role="th">THA</th>
<th data-quarto-table-cell-role="th">TJK</th>
<th data-quarto-table-cell-role="th">TLS</th>
<th data-quarto-table-cell-role="th">TON</th>
<th data-quarto-table-cell-role="th">TTO</th>
<th data-quarto-table-cell-role="th">TUN</th>
<th data-quarto-table-cell-role="th">TUR</th>
<th data-quarto-table-cell-role="th">TZA</th>
<th data-quarto-table-cell-role="th">UGA</th>
<th data-quarto-table-cell-role="th">UKR</th>
<th data-quarto-table-cell-role="th">URY</th>
<th data-quarto-table-cell-role="th">USA</th>
<th data-quarto-table-cell-role="th">UZB</th>
<th data-quarto-table-cell-role="th">VCT</th>
<th data-quarto-table-cell-role="th">VEN</th>
<th data-quarto-table-cell-role="th">VNM</th>
<th data-quarto-table-cell-role="th">VUT</th>
<th data-quarto-table-cell-role="th">YEM</th>
<th data-quarto-table-cell-role="th">ZAF</th>
<th data-quarto-table-cell-role="th">ZMB</th>
<th data-quarto-table-cell-role="th">ZWE</th>
</tr>
<tr class="even">
<th>i64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>…</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
<th>f64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2003</td>
<td>0.87978</td>
<td>1.95054</td>
<td>35.278</td>
<td>74.6812</td>
<td>70.8971</td>
<td>20.4096</td>
<td>3.76374</td>
<td>72.3885</td>
<td>89.5526</td>
<td>12.5837</td>
<td>0.90868</td>
<td>82.9377</td>
<td>2.98462</td>
<td>1.81994</td>
<td>0.96829</td>
<td>44.8576</td>
<td>54.6188</td>
<td>36.4188</td>
<td>25.7218</td>
<td>11.4045</td>
<td>22.899</td>
<td>14.1298</td>
<td>25.6741</td>
<td>52.6759</td>
<td>51.1674</td>
<td>0.35363</td>
<td>25.0588</td>
<td>0.97488</td>
<td>41.7477</td>
<td>84.3941</td>
<td>45.3566</td>
<td>20.8536</td>
<td>6.69626</td>
<td>6.66446</td>
<td>2.25179</td>
<td>9.57701</td>
<td>…</td>
<td>7.29792</td>
<td>86.4376</td>
<td>0.22739</td>
<td>19.1676</td>
<td>60.6975</td>
<td>2.01834</td>
<td>3.133</td>
<td>33.2775</td>
<td>68.4271</td>
<td>87.2851</td>
<td>98.2426</td>
<td>7.9685</td>
<td>56.563</td>
<td>6.62407</td>
<td>0.68509</td>
<td>4.38771</td>
<td>33.3244</td>
<td>0.71512</td>
<td>2.18764</td>
<td>10.7214</td>
<td>25.1251</td>
<td>19.0389</td>
<td>41.1128</td>
<td>3.49964</td>
<td>2.94538</td>
<td>13.6577</td>
<td>15.1631</td>
<td>55.4096</td>
<td>1.24776</td>
<td>55.6041</td>
<td>27.093</td>
<td>3.44629</td>
<td>3.88551</td>
<td>3.14667</td>
<td>34.7626</td>
<td>2.19418</td>
<td>2.97287</td>
</tr>
<tr class="even">
<td>2004</td>
<td>2.54662</td>
<td>3.9784</td>
<td>40.6495</td>
<td>78.5281</td>
<td>83.1597</td>
<td>34.8114</td>
<td>6.72643</td>
<td>82.2081</td>
<td>97.7795</td>
<td>17.156</td>
<td>1.37553</td>
<td>87.6255</td>
<td>5.62957</td>
<td>2.93277</td>
<td>1.94647</td>
<td>61.0333</td>
<td>74.5619</td>
<td>54.743</td>
<td>33.9881</td>
<td>23.0022</td>
<td>27.6052</td>
<td>19.5647</td>
<td>35.9135</td>
<td>74.8745</td>
<td>57.3669</td>
<td>2.94185</td>
<td>28.9318</td>
<td>1.43102</td>
<td>46.7437</td>
<td>84.9756</td>
<td>57.2138</td>
<td>25.7141</td>
<td>8.54469</td>
<td>9.21627</td>
<td>3.49263</td>
<td>10.76</td>
<td>…</td>
<td>10.2163</td>
<td>95.6368</td>
<td>0.6321</td>
<td>30.5192</td>
<td>60.5787</td>
<td>4.86334</td>
<td>4.91107</td>
<td>41.4107</td>
<td>79.5226</td>
<td>92.7311</td>
<td>97.6783</td>
<td>13.5115</td>
<td>61.6736</td>
<td>12.7939</td>
<td>1.23991</td>
<td>5.83805</td>
<td>41.1989</td>
<td>1.98806</td>
<td>2.76856</td>
<td>15.6085</td>
<td>48.4019</td>
<td>36.7464</td>
<td>50.5995</td>
<td>5.09582</td>
<td>4.29039</td>
<td>29.0897</td>
<td>18.2681</td>
<td>63.1242</td>
<td>2.09033</td>
<td>63.81</td>
<td>31.9693</td>
<td>6.17384</td>
<td>5.10619</td>
<td>6.68019</td>
<td>42.536</td>
<td>4.09548</td>
<td>3.4429</td>
</tr>
<tr class="odd">
<td>2005</td>
<td>4.91711</td>
<td>8.35159</td>
<td>49.7453</td>
<td>83.3882</td>
<td>97.1993</td>
<td>56.4973</td>
<td>10.5791</td>
<td>90.7636</td>
<td>105.296</td>
<td>26.0781</td>
<td>2.01653</td>
<td>91.6576</td>
<td>7.07639</td>
<td>4.54743</td>
<td>6.21909</td>
<td>81.1551</td>
<td>82.2539</td>
<td>66.2329</td>
<td>38.9203</td>
<td>42.4035</td>
<td>34.3187</td>
<td>25.8676</td>
<td>46.6789</td>
<td>76.7344</td>
<td>64.8898</td>
<td>5.43918</td>
<td>30.6424</td>
<td>2.33165</td>
<td>52.4553</td>
<td>91.959</td>
<td>64.6505</td>
<td>30.0304</td>
<td>11.7071</td>
<td>13.1922</td>
<td>4.67216</td>
<td>15.101</td>
<td>…</td>
<td>15.3986</td>
<td>102.723</td>
<td>1.24203</td>
<td>40.1585</td>
<td>60.0238</td>
<td>4.69738</td>
<td>7.39487</td>
<td>44.8256</td>
<td>84.4454</td>
<td>88.0975</td>
<td>100.822</td>
<td>18.5353</td>
<td>65.8773</td>
<td>15.6797</td>
<td>2.03329</td>
<td>7.41937</td>
<td>46.1397</td>
<td>3.82687</td>
<td>3.48746</td>
<td>28.2689</td>
<td>68.3489</td>
<td>55.3921</td>
<td>62.901</td>
<td>7.56468</td>
<td>4.70367</td>
<td>64.0054</td>
<td>35.1492</td>
<td>68.8835</td>
<td>2.73172</td>
<td>62.8012</td>
<td>46.6505</td>
<td>11.8306</td>
<td>6.02202</td>
<td>9.99364</td>
<td>68.6198</td>
<td>8.10286</td>
<td>5.18375</td>
</tr>
<tr class="even">
<td>2006</td>
<td>9.9133</td>
<td>15.2614</td>
<td>62.6026</td>
<td>86.7048</td>
<td>110.185</td>
<td>79.5273</td>
<td>42.1272</td>
<td>95.9663</td>
<td>112.226</td>
<td>38.1512</td>
<td>2.54273</td>
<td>93.3538</td>
<td>12.1442</td>
<td>7.07267</td>
<td>13.0671</td>
<td>108.025</td>
<td>91.2343</td>
<td>72.6192</td>
<td>46.4606</td>
<td>62.0314</td>
<td>40.9896</td>
<td>30.2062</td>
<td>53.5317</td>
<td>87.8212</td>
<td>82.6517</td>
<td>12.2359</td>
<td>43.9084</td>
<td>2.5128</td>
<td>57.2331</td>
<td>99.4337</td>
<td>75.4174</td>
<td>34.9802</td>
<td>19.7861</td>
<td>17.8682</td>
<td>7.28434</td>
<td>23.9093</td>
<td>…</td>
<td>25.9356</td>
<td>108.658</td>
<td>1.42394</td>
<td>64.1687</td>
<td>60.0857</td>
<td>5.01116</td>
<td>11.1231</td>
<td>60.9527</td>
<td>91.0056</td>
<td>90.8372</td>
<td>105.797</td>
<td>23.0535</td>
<td>77.833</td>
<td>23.8071</td>
<td>4.35335</td>
<td>11.7791</td>
<td>60.2777</td>
<td>30.4638</td>
<td>5.02766</td>
<td>28.2825</td>
<td>111.783</td>
<td>70.9333</td>
<td>75.1837</td>
<td>13.9199</td>
<td>6.97652</td>
<td>105.277</td>
<td>70.8316</td>
<td>76.8586</td>
<td>9.47736</td>
<td>78.2349</td>
<td>69.0163</td>
<td>22.9925</td>
<td>6.94692</td>
<td>12.6482</td>
<td>79.3267</td>
<td>13.713</td>
<td>6.71982</td>
</tr>
<tr class="odd">
<td>2007</td>
<td>18.0167</td>
<td>23.8782</td>
<td>76.8284</td>
<td>77.559</td>
<td>137.458</td>
<td>100.962</td>
<td>63.0765</td>
<td>101.458</td>
<td>119.466</td>
<td>51.1876</td>
<td>3.30806</td>
<td>101.06</td>
<td>22.9147</td>
<td>12.5405</td>
<td>23.2247</td>
<td>130.455</td>
<td>105.539</td>
<td>105.849</td>
<td>61.0557</td>
<td>72.7795</td>
<td>39.9574</td>
<td>33.5993</td>
<td>64.1626</td>
<td>94.953</td>
<td>98.7233</td>
<td>22.0203</td>
<td>60.2637</td>
<td>7.61859</td>
<td>61.2755</td>
<td>108.793</td>
<td>83.7065</td>
<td>41.2808</td>
<td>35.5088</td>
<td>25.1303</td>
<td>10.551</td>
<td>32.349</td>
<td>…</td>
<td>30.8471</td>
<td>128.882</td>
<td>2.17932</td>
<td>102.122</td>
<td>59.6944</td>
<td>5.29914</td>
<td>17.7366</td>
<td>71.5609</td>
<td>112.852</td>
<td>95.7428</td>
<td>110.588</td>
<td>34.8399</td>
<td>84.4864</td>
<td>29.8537</td>
<td>8.28717</td>
<td>19.2349</td>
<td>78.945</td>
<td>29.6445</td>
<td>7.78345</td>
<td>43.5929</td>
<td>110.578</td>
<td>75.1086</td>
<td>87.5976</td>
<td>19.9153</td>
<td>14.1477</td>
<td>119.088</td>
<td>91.174</td>
<td>82.5923</td>
<td>21.0203</td>
<td>99.0675</td>
<td>86.1507</td>
<td>53.835</td>
<td>11.75</td>
<td>17.8838</td>
<td>83.715</td>
<td>21.0029</td>
<td>9.57239</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>59.8109</td>
<td>42.4589</td>
<td>93.8031</td>
<td>109.915</td>
<td>214.842</td>
<td>131.224</td>
<td>123.0</td>
<td>110.033</td>
<td>124.23</td>
<td>102.987</td>
<td>53.2737</td>
<td>100.164</td>
<td>76.408</td>
<td>94.622</td>
<td>98.9289</td>
<td>119.395</td>
<td>139.735</td>
<td>98.9789</td>
<td>102.187</td>
<td>122.57</td>
<td>64.7802</td>
<td>99.4566</td>
<td>101.602</td>
<td>117.319</td>
<td>129.268</td>
<td>92.6023</td>
<td>147.065</td>
<td>26.2216</td>
<td>89.0495</td>
<td>126.681</td>
<td>133.27</td>
<td>116.229</td>
<td>123.098</td>
<td>74.3995</td>
<td>40.5014</td>
<td>91.189</td>
<td>…</td>
<td>104.056</td>
<td>152.074</td>
<td>67.9775</td>
<td>151.669</td>
<td>111.5</td>
<td>49.5263</td>
<td>77.3644</td>
<td>125.48</td>
<td>133.04</td>
<td>119.153</td>
<td>124.086</td>
<td>89.2004</td>
<td>155.551</td>
<td>87.4952</td>
<td>43.2279</td>
<td>74.3997</td>
<td>175.266</td>
<td>107.442</td>
<td>115.089</td>
<td>102.246</td>
<td>134.143</td>
<td>125.533</td>
<td>94.9086</td>
<td>75.7302</td>
<td>58.8754</td>
<td>127.754</td>
<td>131.363</td>
<td>103.935</td>
<td>71.7444</td>
<td>107.164</td>
<td>69.55</td>
<td>146.138</td>
<td>88.1403</td>
<td>44.8811</td>
<td>157.692</td>
<td>86.0723</td>
<td>85.8627</td>
</tr>
<tr class="even">
<td>2019</td>
<td>59.6471</td>
<td>45.8065</td>
<td>91.1635</td>
<td>114.953</td>
<td>209.033</td>
<td>125.303</td>
<td>124.614</td>
<td>109.753</td>
<td>120.776</td>
<td>106.328</td>
<td>53.2996</td>
<td>100.165</td>
<td>81.3235</td>
<td>97.1499</td>
<td>100.4</td>
<td>116.617</td>
<td>129.143</td>
<td>107.812</td>
<td>112.255</td>
<td>123.23</td>
<td>66.0705</td>
<td>100.149</td>
<td>97.3747</td>
<td>117.112</td>
<td>129.845</td>
<td>95.3473</td>
<td>160.662</td>
<td>32.2627</td>
<td>90.9589</td>
<td>126.921</td>
<td>130.493</td>
<td>122.67</td>
<td>132.574</td>
<td>83.9044</td>
<td>39.94</td>
<td>91.0654</td>
<td>…</td>
<td>109.342</td>
<td>159.347</td>
<td>65.662</td>
<td>167.089</td>
<td>111.823</td>
<td>51.3194</td>
<td>77.6791</td>
<td>134.349</td>
<td>135.756</td>
<td>120.569</td>
<td>125.457</td>
<td>91.0519</td>
<td>164.617</td>
<td>87.1297</td>
<td>45.9379</td>
<td>73.7225</td>
<td>181.222</td>
<td>115.373</td>
<td>109.555</td>
<td>58.7722</td>
<td>145.716</td>
<td>124.387</td>
<td>94.6498</td>
<td>80.5836</td>
<td>59.0598</td>
<td>130.629</td>
<td>133.237</td>
<td>105.321</td>
<td>101.26</td>
<td>92.5178</td>
<td>63.8474</td>
<td>140.193</td>
<td>90.8331</td>
<td>43.399</td>
<td>162.739</td>
<td>93.0148</td>
<td>86.4094</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>58.0461</td>
<td>43.7804</td>
<td>91.1881</td>
<td>103.877</td>
<td>194.468</td>
<td>121.181</td>
<td>120.682</td>
<td>104.93</td>
<td>120.132</td>
<td>101.597</td>
<td>52.5571</td>
<td>99.9101</td>
<td>85.2391</td>
<td>102.973</td>
<td>106.002</td>
<td>114.597</td>
<td>119.412</td>
<td>117.717</td>
<td>106.375</td>
<td>125.165</td>
<td>67.5517</td>
<td>99.8988</td>
<td>98.6456</td>
<td>104.722</td>
<td>119.934</td>
<td>96.7703</td>
<td>161.859</td>
<td>36.426</td>
<td>84.7748</td>
<td>127.376</td>
<td>129.414</td>
<td>120.497</td>
<td>138.664</td>
<td>85.2722</td>
<td>42.5028</td>
<td>97.6561</td>
<td>…</td>
<td>113.638</td>
<td>150.259</td>
<td>63.6671</td>
<td>159.575</td>
<td>112.169</td>
<td>53.1133</td>
<td>80.1173</td>
<td>146.875</td>
<td>133.633</td>
<td>121.331</td>
<td>123.549</td>
<td>104.747</td>
<td>152.545</td>
<td>79.1482</td>
<td>50.4343</td>
<td>75.164</td>
<td>162.328</td>
<td>118.819</td>
<td>103.911</td>
<td>58.6544</td>
<td>134.231</td>
<td>124.042</td>
<td>95.3961</td>
<td>84.0051</td>
<td>62.2824</td>
<td>129.341</td>
<td>133.902</td>
<td>103.855</td>
<td>99.4064</td>
<td>96.9438</td>
<td>58.1626</td>
<td>141.656</td>
<td>82.391</td>
<td>42.0038</td>
<td>158.447</td>
<td>100.235</td>
<td>84.9604</td>
</tr>
<tr class="even">
<td>2021</td>
<td>56.6945</td>
<td>44.3869</td>
<td>92.4843</td>
<td>119.688</td>
<td>186.301</td>
<td>130.353</td>
<td>125.395</td>
<td>105.119</td>
<td>121.358</td>
<td>105.694</td>
<td>59.7008</td>
<td>101.463</td>
<td>94.9183</td>
<td>112.198</td>
<td>110.012</td>
<td>114.912</td>
<td>128.079</td>
<td>100.257</td>
<td>114.912</td>
<td>127.117</td>
<td>66.7769</td>
<td>100.809</td>
<td>104.825</td>
<td>112.223</td>
<td>133.597</td>
<td>100.331</td>
<td>173.252</td>
<td>35.817</td>
<td>87.4056</td>
<td>123.212</td>
<td>136.572</td>
<td>121.492</td>
<td>150.344</td>
<td>80.8081</td>
<td>47.2883</td>
<td>95.8615</td>
<td>…</td>
<td>115.325</td>
<td>157.978</td>
<td>62.1565</td>
<td>176.973</td>
<td>115.701</td>
<td>51.2059</td>
<td>85.2578</td>
<td>146.654</td>
<td>135.268</td>
<td>123.363</td>
<td>124.961</td>
<td>118.627</td>
<td>149.479</td>
<td>78.5558</td>
<td>58.0323</td>
<td>70.4497</td>
<td>168.485</td>
<td>116.225</td>
<td>102.669</td>
<td>60.9802</td>
<td>134.222</td>
<td>129.846</td>
<td>99.5415</td>
<td>86.0163</td>
<td>65.6221</td>
<td>135.026</td>
<td>138.113</td>
<td>106.325</td>
<td>102.41</td>
<td>95.5174</td>
<td>60.2345</td>
<td>136.806</td>
<td>81.6914</td>
<td>47.809</td>
<td>163.128</td>
<td>103.283</td>
<td>90.2538</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>56.2655</td>
<td>66.6008</td>
<td>98.395</td>
<td>142.426</td>
<td>195.625</td>
<td>131.484</td>
<td>130.54</td>
<td>109.469</td>
<td>121.166</td>
<td>107.506</td>
<td>56.26</td>
<td>101.68</td>
<td>105.745</td>
<td>119.463</td>
<td>109.867</td>
<td>116.679</td>
<td>139.636</td>
<td>101.624</td>
<td>118.944</td>
<td>128.315</td>
<td>67.175</td>
<td>101.572</td>
<td>101.245</td>
<td>114.581</td>
<td>116.108</td>
<td>95.1298</td>
<td>178.205</td>
<td>38.8218</td>
<td>91.2387</td>
<td>123.971</td>
<td>135.114</td>
<td>124.195</td>
<td>161.232</td>
<td>89.8274</td>
<td>48.6774</td>
<td>93.6259</td>
<td>…</td>
<td>118.15</td>
<td>173.005</td>
<td>62.0735</td>
<td>183.249</td>
<td>120.27</td>
<td>49.6801</td>
<td>86.7785</td>
<td>149.052</td>
<td>136.029</td>
<td>126.459</td>
<td>140.782</td>
<td>121.492</td>
<td>163.43</td>
<td>78.6568</td>
<td>65.4378</td>
<td>72.2148</td>
<td>176.223</td>
<td>126.161</td>
<td>108.158</td>
<td>61.7258</td>
<td>133.632</td>
<td>131.875</td>
<td>103.721</td>
<td>93.016</td>
<td>70.1401</td>
<td>120.261</td>
<td>139.829</td>
<td>108.786</td>
<td>105.472</td>
<td>102.334</td>
<td>66.4668</td>
<td>137.852</td>
<td>81.6203</td>
<td>46.4534</td>
<td>160.729</td>
<td>98.4373</td>
<td>88.9958</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>Now, what if we want to go the other way? That is, suppose we stored the data originally in the format above (<code>cell_wide</code>) but want to return to the version we started with. This can be achieved by using the <code>.unpivot()</code> method, which requires specifying the index column to use. The new columns created to store the data are given the default names <code>variable</code> and <code>value</code>. These can be changed by setting the <code>variable_name</code> and <code>value_name</code> arguments.</p>
<div id="72660f7f" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  cell_wide</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  .unpivot(index<span class="op">=</span><span class="st">"year"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (3_480, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">variable</th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
<tr class="even">
<th>i64</th>
<th>str</th>
<th>f64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2003</td>
<td>"AFG"</td>
<td>0.87978</td>
</tr>
<tr class="even">
<td>2004</td>
<td>"AFG"</td>
<td>2.54662</td>
</tr>
<tr class="odd">
<td>2005</td>
<td>"AFG"</td>
<td>4.91711</td>
</tr>
<tr class="even">
<td>2006</td>
<td>"AFG"</td>
<td>9.9133</td>
</tr>
<tr class="odd">
<td>2007</td>
<td>"AFG"</td>
<td>18.0167</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>"ZWE"</td>
<td>85.8627</td>
</tr>
<tr class="even">
<td>2019</td>
<td>"ZWE"</td>
<td>86.4094</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>"ZWE"</td>
<td>84.9604</td>
</tr>
<tr class="even">
<td>2021</td>
<td>"ZWE"</td>
<td>90.2538</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>"ZWE"</td>
<td>88.9958</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pivot and unpivot syntax
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The current version of Polars on Google Colab does not allow using the <code>c.</code> notation when specifying columns as we do with other Polars methods. Instead, you must specify the column as a string, similar to how we do it in plotnine graphics. This has already been changed in the development version of Polars for <code>pivot</code> and will likely change for <code>unpivot</code> in the near future. For now, remember that both <code>pivot</code> and <code>unpivot</code> require a different way of specifying columns compared to other Polars methods.</p>
</div>
</div>
</div>
<p>The <code>.pivot()</code> and <code>.unpivot()</code> methods are powerful tools for data manipulation and constitute the final major methods we need for manipulating tabular datasets. Although they may at first glance seem straightforward (and should be, at least in theory), care is needed when using them to reshape data, because they can easily introduce subtle errors. The best practice is to decide on the unit of observation up front and structure your data accordingly. Use these reshaping functions when necessary, but avoid unnecessary back-and-forth transformations that can introduce mistakes.</p>
</section>
<section id="expand-list-columns" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="expand-list-columns"><span class="header-section-number">4.9</span> Expand List Columns</h2>
<p>A final type of transformation arises when multiple elements occupy a single cell in a table. This usually occurs only after a data-cleaning step we’ve performed, rather than as raw input from a CSV file. For example, the function <code>str.split</code>, which we’ll learn more about in <a href="07_strings.html" class="quarto-xref"><span>Chapter 7</span></a>, can split the text in a DataFrame column into parts. We can use this to split the multiple language codes found in the <code>lang</code> column of our data.</p>
<div id="cd05d2cb" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    country</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    .select(c.full_name, c.lang)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    .with_columns(</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>        lang_codes <span class="op">=</span> c.lang.<span class="bu">str</span>.split(<span class="st">"|"</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (135, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">full_name</th>
<th data-quarto-table-cell-role="th">lang</th>
<th data-quarto-table-cell-role="th">lang_codes</th>
</tr>
<tr class="even">
<th>str</th>
<th>str</th>
<th>list[str]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Senegal"</td>
<td>"pbp|fra|wol"</td>
<td>["pbp", "fra", "wol"]</td>
</tr>
<tr class="even">
<td>"Venezuela, Bolivarian Republic…</td>
<td>"spa|vsl"</td>
<td>["spa", "vsl"]</td>
</tr>
<tr class="odd">
<td>"Finland"</td>
<td>"fin|swe"</td>
<td>["fin", "swe"]</td>
</tr>
<tr class="even">
<td>"United States of America"</td>
<td>"eng"</td>
<td>["eng"]</td>
</tr>
<tr class="odd">
<td>"Sri Lanka"</td>
<td>"sin|sin|tam|tam"</td>
<td>["sin", "sin", … "tam"]</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"Albania"</td>
<td>"sqi"</td>
<td>["sqi"]</td>
</tr>
<tr class="even">
<td>"Malaysia"</td>
<td>"msa"</td>
<td>["msa"]</td>
</tr>
<tr class="odd">
<td>"El Salvador"</td>
<td>"spa"</td>
<td>["spa"]</td>
</tr>
<tr class="even">
<td>"Cyprus"</td>
<td>"ell|tur"</td>
<td>["ell", "tur"]</td>
</tr>
<tr class="odd">
<td>"Pakistan"</td>
<td>"eng|urd"</td>
<td>["eng", "urd"]</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>It is hard to work directly with the embedding list structure. Often the easiest way to simplify a data frame that contains list elements is to unravel the lists, duplicating the other columns. Use the <code>.explode()</code> method, passing the column(s) you want to unravel.</p>
<div id="2a9fc606" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    country</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    .select(c.full_name, c.lang)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    .with_columns(</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>        lang_codes <span class="op">=</span> c.lang.<span class="bu">str</span>.split(<span class="st">"|"</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    .explode(c.lang_codes)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div><style>
.dataframe > thead > tr,
.dataframe > tbody > tr {
  text-align: right;
  white-space: pre-wrap;
}
</style>
<small>shape: (265, 3)</small>
<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">full_name</th>
<th data-quarto-table-cell-role="th">lang</th>
<th data-quarto-table-cell-role="th">lang_codes</th>
</tr>
<tr class="even">
<th>str</th>
<th>str</th>
<th>str</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>"Senegal"</td>
<td>"pbp|fra|wol"</td>
<td>"pbp"</td>
</tr>
<tr class="even">
<td>"Senegal"</td>
<td>"pbp|fra|wol"</td>
<td>"fra"</td>
</tr>
<tr class="odd">
<td>"Senegal"</td>
<td>"pbp|fra|wol"</td>
<td>"wol"</td>
</tr>
<tr class="even">
<td>"Venezuela, Bolivarian Republic…</td>
<td>"spa|vsl"</td>
<td>"spa"</td>
</tr>
<tr class="odd">
<td>"Venezuela, Bolivarian Republic…</td>
<td>"spa|vsl"</td>
<td>"vsl"</td>
</tr>
<tr class="even">
<td>…</td>
<td>…</td>
<td>…</td>
</tr>
<tr class="odd">
<td>"El Salvador"</td>
<td>"spa"</td>
<td>"spa"</td>
</tr>
<tr class="even">
<td>"Cyprus"</td>
<td>"ell|tur"</td>
<td>"ell"</td>
</tr>
<tr class="odd">
<td>"Cyprus"</td>
<td>"ell|tur"</td>
<td>"tur"</td>
</tr>
<tr class="even">
<td>"Pakistan"</td>
<td>"eng|urd"</td>
<td>"eng"</td>
</tr>
<tr class="odd">
<td>"Pakistan"</td>
<td>"eng|urd"</td>
<td>"urd"</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The term “explode” warns us that the resulting dataset can become very large, particularly if we unravel multiple columns simultaneously.</p>
</section>
<section id="coming-from-r-or-pandas" class="level2" data-number="4.10">
<h2 data-number="4.10" class="anchored" data-anchor-id="coming-from-r-or-pandas"><span class="header-section-number">4.10</span> Coming from R or Pandas</h2>
<p>If you are familiar with joins and pivots in R’s <code>dplyr</code> or in Pandas, the code here should be relatively familiar, except for the specific defaults and argument names. What makes these operations difficult are the concepts, not the code, and those do not change across implementations.</p>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/taylor-arnold\.github\.io\/fds-py");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_graphics.html" class="pagination-link" aria-label="EDA II: Visualizing Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">EDA II: Visualizing Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05_collect.html" class="pagination-link" aria-label="EDA IV: Collecting Data">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">EDA IV: Collecting Data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Taylor Arnold</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>A <a href="https://distantviewing.org/">Distant Viewing Lab</a> project</p>
</div>
  </div>
</footer>




</body></html>